AllCops:
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Exclude:
    - 'config/**'
    - 'config/**/*'
  Max: 100

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
